### PR TITLE
Deprecated the support of Silver light and XBAP from the root version

### PR DESCRIPTION
**Pull request by SandeepNayak077**
Removed the following projects

- WSClientSL_samples
- WSClientWPFbap_sample

And also removed the build system related to Silverlight and XBAP projects.

### CODE REVIEW

**Comment by daisukenishino** [comment]
@yusukemaegawa 

Please check that there are no problems.
If there is no problem, I will send the pullrequest to OpenTouryoProject after merge this.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

If you want to finish support for Silverlight and XBAP, you should modify the several descriptions.

For example:
[README.md](https://github.com/SymphonyTeleca/OpenTouryo/blob/del_SL_XBAP/root/README.md)
```md
   - C/S 3階層の場合(In the case of three-tier C/S)：
      - Windows Forms
         C:\root\programs\C#\Samples\WS_sample\WSClient_sample\WSClientWin_sample\WSClientWin_sample.sln
         C:\root\programs\C#\Samples\WS_sample\WSClient_sample\WSClientWinCone_sample\WSClientWinCone_sample.sln
      - WPF
         C:\root\programs\C#\Samples\WS_sample\WSClient_sample\WSClientWPF_sample\WSClientWPF_sample.sln
         C:\root\programs\C#\Samples\WS_sample\WSClient_sample\WSClientWPFbap_sample\WSClientWPFbap_sample.sln
    
   - Silverlight の場(In the case of Silverlight)：
      C:\root\programs\C#\Samples\WS_sample\WSClient_sample\WSClientSL_samples\WSClientSL_samples.sln
```

There may be a similar description other than this.
Will you check the descriptions of Silverlight and XBAP?

**Comment by daisukenishino** [comment]
@yusukemaegawa 

I will add following description to the readme.md and pukiwiki separately.

```TXT
XBAP and Silverlight have been removed from version "01-72" or more.
```

**Comment by yusukemaegawa** [comment]
@daisukenishino 

> https://github.com/SymphonyTeleca/OpenTouryo/pull/99#issuecomment-191535909

I think that you have two things to do.
- Specify the finishing support for Silverlight and XBAP.
(e.g. We have finished support for Silverlight and XBAP.)
- Remove the description of Silverlight and XBAP.
(e.g. Readme.md)

**Comment by daisukenishino** [comment]
@yusukemaegawa 

I understood it. I will do it separately.
Therefor, please merge this pull request if there is no problem.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

> I think that you have two things to do.
> - Specify the finishing support for Silverlight and XBAP.  
> (e.g. We have finished support for Silverlight and XBAP.)
> - Remove the description of Silverlight and XBAP.  
> (e.g. Readme.md)

I think the above is problem.
If the support for Silverlight and XBAP have been finished, project owner should announce at once.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

see : https://github.com/SymphonyTeleca/OpenTouryo/pull/99/files#diff-4c1b442be58d89a500824645348c3cda

And the announcement is done at the time of tagging. please merge.

**Pull request merged**
