### PR TITLE
Resoved issues

### PR DESCRIPTION
**Pull request by supragyan**
Done changes for Problem of "suppress submit by pressing enter key."
1.Implemented code to check submit by pressing Enter key in ie_key_event.js page.

Done Implemented for "Support of event handling of the TextBox Class".
1.Implemented code in BaseController.cs, FxCmnFunction.cs,FxLiteral.cs,app.config,testScreen2.aspx.cs page.

### CODE REVIEW

**Comment by daisukenishino** [comment]
Divides the feature branch for every problem, Please send two PullRequest.
Please check the following CONTRIBUTING.md.
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/CONTRIBUTING.md

**Comment by supragyan** [comment]
Dear Nishino-San,

>>Divides the feature branch for every problem, Please send two PullRequest.
<HODC Understanding>
HODC will create two feature branch for
1>Suppress submit by pressing enter key."
2>Support of TextBox.TextChanged event handeling for TextBox class.
Please confirm.

On Mon, Apr 20, 2015 at 6:49 AM, daisuke nishino <notifications@github.com>
wrote:

> Closed #25 <https://github.com/SymphonyTeleca/OpenTouryo/pull/25>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SymphonyTeleca/OpenTouryo/pull/25#event-284839030>.
>



-- 
Hi,
   I attached my CV for your Reference

   I am Supragyan having MCA( 2011 batch) with 7.5CGPA . I am good in
technical as  well as      communication so its my will to join your
company, utilize my skill & be a part of your growth .Still now I am not a
experienced one  but  I am very much efficient  & dedicated to my work. So
I want  a opportunity  from Ur  side to prove myself.  Now  I am  waiting
for your  response......

  With Regards
  Supragyan Panda
  07416374375

**Comment by daisukenishino** [comment]
As you say, you must create the following two feature branch.
- Suppress submit by pressing enter key.
- Support of TextBox.TextChanged event handeling for TextBox class.

**Comment by supragyan** [comment]
[Visit GitHub!](https://github.com/SymphonyTeleca/OpenTouryo/blob/TextBoxEventHandler/root/programs/C%23/Frameworks/Infrastructure/Framework/Presentation/BaseController.cs#L1405)

**Comment by supragyan** [comment]
[Visit GitHub!](BaseController.cs.https://github.com/SymphonyTeleca/OpenTouryo/blob/TextBoxEventHandler/root/programs/C%23/Frameworks/Infrastructure/Framework/Presentation/BaseController.cs#L1405)

[base!](https://github.com/SymphonyTeleca/OpenTouryo/blob/TextBoxEventHandler/root/programs/C%23/Frameworks/Infrastructure/Framework/Presentation/BaseController.cs#L1405)

**Comment by supragyan** [comment]
Dear Nishino-San,
HODC created feature branch 'SubmitByEnterKey' and 'TextBoxEventHandler' for  "suppress submit by pressing enter key." and "Support of event handling of the TextBox Class" task in GitHub and also recreated pullrequests.
File Location: 
[SubmitButton PullRequest](https://github.com/SymphonyTeleca/OpenTouryo/pull/27)
[TextBoxEventHandler Pullrequest](https://github.com/SymphonyTeleca/OpenTouryo/pull/28)

Please confirm.

**Comment by supragyan** [comment]
Dear Nishino-San,
HODC created feature branch 'SubmitByEnterKey' and 'TextBoxEventHandler' for "suppress submit by pressing enter key." and "Support of event handling of the TextBox Class" task in GitHub and also recreated pullrequests.
File Location: 
[TextBoxEventHandler Pullrequest](https://github.com/SymphonyTeleca/OpenTouryo/pull/27)
[SubmitButton PullRequest](https://github.com/SymphonyTeleca/OpenTouryo/pull/28)

Please confirm.

**Comment by supragyan** [comment]
HODC did mark down on ie_key_event.js file changes for "suppress submit by pressing enter key." 
[ie_key_event.js](https://github.com/SymphonyTeleca/OpenTouryo/blob/SubmitByEnterKey/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Framework/Js/ie_key_event.js#L238-L261)

Please confirm.

**Comment by supragyan** [comment]
1.HODC  added constant value for prefix and event of text box control in FxLiteral.cs.
[FxLiteral.cs](https://github.com/SymphonyTeleca/OpenTouryo/blob/SubmitByEnterKey/root/programs/C%23/Frameworks/Infrastructure/Framework/Util/FxLiteral.cs#L244)
[FxLiteral.cs](https://github.com/SymphonyTeleca/OpenTouryo/blob/TextBoxEventHandler/root/programs/C%23/Frameworks/Infrastructure/Framework/Util/FxLiteral.cs#L334)

2.In BaseController.cs, 
   HODC Created TextChanged event handler 
  [BaseController.cs]  (https://github.com/SymphonyTeleca/OpenTouryo/blob/TextBoxEventHandler/root/programs/C%23/Frameworks/Infrastructure/Framework/Presentation/BaseController.cs#L2043-L2054)
  Implemented code for adding TextChanged event handler to Dictionary.
  [BaseController.cs] (https://github.com/SymphonyTeleca/OpenTouryo/blob/TextBoxEventHandler/root/programs/C%23/ Frameworks/Infrastructure/Framework/Presentation/BaseController.cs#L1405-L1410)

3.Implemented code for adding TextChanged eventHandler to TextBox control in FxCmnFunction.cs.
[FxCmnFunction.cs](https://github.com/SymphonyTeleca/OpenTouryo/blob/TextBoxEventHandler/root/programs/C%23/Frameworks/Infrastructure/Framework/Util/FxCmnFunction.cs#L367-L378)

4.Added key value pair for textbox control in app.config file.
[app.config](https://github.com/SymphonyTeleca/OpenTouryo/blob/TextBoxEventHandler/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/app.config#L21)

5.Added test code in testScreen2.aspx.cs. 
[testScreen2.aspx.cs](https://github.com/SymphonyTeleca/OpenTouryo/blob/TextBoxEventHandler/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Aspx/testFxLayerP/normal/testScreen2.aspx.cs#L528-L534)

Please review and confirm.

**Comment by daisukenishino** [comment]
>>https://github.com/SymphonyTeleca/OpenTouryo/pull/25#issuecomment-94472688

Did you confirm that works as specification by the test ?
There is no problem if it work as specification.

**Comment by supragyan** [comment]
Dear Nishino-San,
HODC did test and it is working as of specification.

**Pull request closed without merging**
