### PR TITLE
Fixed the issue of grid view row replacement.

### PR DESCRIPTION
**Pull request by svkumar2810**
1. Modified gridview selected index changing method to handle the grid view row selection during paging in _Screen_ConditionalSearch.aspx.cs
2.  Modified UOC_gvwGridView1_RowCommand to fix gridview row replacement issue in _Screen_SearchAndUpdate.aspx.cs.
3. Modified UOC_gvwGridView1_RowCommand to fix gridview row replacement issue in _Screen_SearchAndUpdate.aspx.vb.
4. Modified the code of 'UOC_BatchUpdateDM' method to perform batch delete operation in single transaction in _3TierEngine.vb

### CODE REVIEW

**Comment by daisukenishino** [comment]
@svkumar2810 

The following two files are in pairs of the C# and VB.
- _Screen_SearchAndUpdate.aspx.cs
- _Screen_SearchAndUpdate.aspx.vb

But, the following files are not paired.
One file is a C#. And, another file is the VB.
- _Screen_ConditionalSearch.aspx.cs
- _3TierEngine.vb

Please explain why these files are not pairs.

**Comment by svkumar2810** [comment]
@daisukenishino 

_Screen_ConditionalSearch.aspx.cs has not merged and it was closed in pull request [#138](https://github.com/SymphonyTeleca/OpenTouryo/pull/138). So I sent it again for merging.

The changes pertaining to _Screen_ConditionalSearch.aspx.vb has already been merged in pull request [#132](https://github.com/SymphonyTeleca/OpenTouryo/pull/132)

There is no change in _3TierEngine.cs so it is not paired with this pull request. As the code change required only in VB and it was already merged. So I modified the code and resent it.

**Comment by daisukenishino** [comment]
@svkumar2810 

>- As the code change required only in VB and it was already merged.

Please tell me the pull-request number that was performed the change to the branch.

**Comment by svkumar2810** [comment]
@daisukenishino 

>Please tell me the pull-request number that was performed the change to the branch.

Refer to Pull request number [#134](https://github.com/SymphonyTeleca/OpenTouryo/pull/134)
**File Name: _3TierEngine.vb**

Here I implemented new method to handle batch update for multiple table in single transaction.
**Method Name: UOC_BatchUpdateDM** 

In this method you can find below piece of code

``` VB
 cmnDao.SetParameter(dc.ColumnName.Replace(TableName & "_", ""), dr(dc, DataRowVersion.Current))
```
As this needs to be changed to **DataRowVersion.Original**. I sent the new pull request [#141](https://github.com/SymphonyTeleca/OpenTouryo/pull/141) by modifying it as below

``` VB
  cmnDao.SetParameter(dc.ColumnName.Replace(TableName & "_", ""), dr(dc, DataRowVersion.Original))
```

**Comment by daisukenishino** [comment]
@svkumar2810 

>https://github.com/SymphonyTeleca/OpenTouryo/pull/141#issuecomment-231346840

I see.

**Pull request merged**
