### PR TITLE
Converted ProjectX_sample website to webapp

### PR DESCRIPTION
**Pull request by supragyan**
Modified as per below to convert ProjectX_sample  website to web application.
1.Deleted ProjectX_sample website and created ProjectX_sample webapp.
2.Included all the files (.aspx,.master,.Css etc) in ProjectX_sample webapp.
3.Added namespace to each Page directive of .aspx page and aspx.cs page. 
4.Modified each class as required to support in webapp.

### CODE REVIEW

**Comment by supragyan** [comment]
@daisukenishino 

In this pull request we have converted ProjectX_sample Website to Webapp in root folder.
And also we are creating evidences for this.Once it is done we will share it by Monday EOD.

**Comment by daisukenishino** [comment]
@supragyan 

>https://github.com/SymphonyTeleca/OpenTouryo/pull/122#issuecomment-220687025
And also we are creating evidences for this.
Once it is done we will share it by Monday EOD.

Thank you for your response.

But, unfortunately,
conflict was caused by https://github.com/SymphonyTeleca/OpenTouryo/pull/123.
Please resolve the conflict in the following procedure.

1. Again branch from nishino branch
2. To reflect this change to the new branch.
3. Merge the changes of https://github.com/SymphonyTeleca/OpenTouryo/pull/123.
4. Please re-send a pull request of this modification to "nishino" branch.

**Comment by supragyan** [comment]
@daisukenishino 

We will do so.

**Comment by supragyan** [comment]
@daisukenishino 
We have created new [#125](https://github.com/SymphonyTeleca/OpenTouryo/pull/125) which also contains  [#123](https://github.com/SymphonyTeleca/OpenTouryo/pull/123) and [#124](https://github.com/SymphonyTeleca/OpenTouryo/pull/124)  changes.

Please review.

**Pull request closed without merging**
