### PR TITLE
Did Enhance of MyBaseMVController

### PR DESCRIPTION
**Pull request by kishoreandukuri**
Did Enhance of MyBaseMVController
OpenTouryoProject#118

1)An erroneous detection of the session time-out
2)Added new constant DUMMY to the class FxHttpSessionIndex.cs
3)Stored dummy value in session to fix the bug in OnActionExecuting method

### CODE REVIEW

**Comment by daisukenishino** [comment]
@kishoreandukuri 
I found a problem of this pullrequest.

```C#
   Session["FxDummy"] = "dummy";
    // 2009/09/18-end
}
else
{
    // セッションタイムアウト検出用Cookie有り
 
    if (cookie.Value == "")
    {
        
        ・・・
        
        // Set-Cookie HTTPヘッダをレスポンス
        Response.Cookies.Set(FxCmnFunction.CreateCookieForSessionTimeoutDetection());
       Session["FxDummy"] = "dummy";
        // 2009/09/18-end
    }
```

Please check the [#118#issuecomment](https://github.com/OpenTouryoProject/OpenTouryo/issues/118#issuecomment-151811153).

You must do similar fixes for the [pullrequest#63](https://github.com/SymphonyTeleca/OpenTouryo/pull/63).

**Comment by daisukenishino** [comment]
> You must do similar fixes for the pullrequest#63.

 I'll correct it

The following pullrequest has been corrected properly.
https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/21/files

```C#
    // Set-Cookie HTTPヘッダをレスポンス
    Response.Cookies.Set(FxCmnFunction.CreateCookieForSessionTimeoutDetection());
    Session[FxHttpSessionIndex.DUMMY] = "dummy";
}
else
{
    // セッションタイムアウト検出用Cookie有り

    if (cookie.Value == "")
    {
        ・・・
        
        // Set-Cookie HTTPヘッダをレスポンス
        Response.Cookies.Set(FxCmnFunction.CreateCookieForSessionTimeoutDetection());
        Session[FxHttpSessionIndex.DUMMY] = "dummy";
```

**Comment by kishoreandukuri** [comment]
@daisukenishino 

we did above changes in pull request #22 of OpenTouryoTemplates repository 

similarly we did above changes in pull request #65 of OpenTouryo  repository 

Do we need do above changes any other files?

Please let us know.

**Comment by daisukenishino** [comment]
@kishoreandukuri 
I'll correct it.

at OpenTouryoTemplates
```C#
Session[FxHttpSessionIndex.DUMMY] = "dummy";
```
at OpenTouryo
```C#
Session["FxDummy"] = "dummy";
```
The above is a problem.

In addition, there is one problem.

When upgrading the Framework,
 it is possible that Session keys compete with the user program side.
```C#
public const string DUMMY = "dummy";
```

There are two measures.
-

**Comment by kishoreandukuri** [comment]
@daisukenishino 

>at OpenTouryo
Session["FxDummy"] = "dummy";

we forgot to chanage. here with Session[FxHttpSessionIndex.DUMMY] = "dummy";

we will do this change and create pull request.

Please confirm.

Please lets us know if anything do we need to change

**Comment by daisukenishino** [comment]
@kishoreandukuri 

Conclusions that is obtained from [here](https://github.com/SymphonyTeleca/OpenTouryo/pull/65#issuecomment-154977733).
- Modifications of BaseController.cs is not required.
- Please modify only FxHttpSessionIndex.cs.

**Comment by kishoreandukuri** [comment]
@daisukenishino 

>Please modify only FxHttpSessionIndex.cs.

shall we remove below in FxHttpSessionIndex.cs?
>public const string DUMMY = "dummy";

Please confirm.

**Comment by daisukenishino** [comment]
@kishoreandukuri 
I do not know [what you want to say](https://github.com/SymphonyTeleca/OpenTouryo/pull/65#issuecomment-155303536).

I am considering as follows.

- By the [above-mentioned reasons](https://github.com/SymphonyTeleca/OpenTouryo/pull/65#issuecomment-154977733), modifications of the BaseController.cs is unnecessary.

- FxHttpSessionIndex.cs should be modified, because there is possibility that the trouble of throwback occur in future merge work.

Did you understand ?

**Comment by kishoreandukuri** [comment]
@daisukenishino 

>FxHttpSessionIndex.cs should be modified, because there is possibility that the trouble of throwback occur in future merge work.

What needs to be modified in FxHttpSessionIndex.cs?

Please let us know.

**Comment by daisukenishino** [comment]
@kishoreandukuri 

>What needs to be modified in FxHttpSessionIndex.cs?

Add the following.

```C#
public const string DUMMY = "dummy";
```

>because there is possibility that the trouble of throwback occur in future merge work.

Therefor, you should apply same changes that you did to the VS2012 at FxHttpSessionIndex.

- https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/21/files
  - https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/3748d8e6ee8ae607dbafef1fee59ca81591f3853/root_VS2012/programs/C%23/Frameworks/Infrastructure/Framework/Util/FxHttpSessionIndex.cs#L73

Did you understand ?

**Comment by kishoreandukuri** [comment]
@daisukenishino 

>Did you understand ?
Yes 
>Therefor, you should apply same changes that you did to the VS2012 at FxHttpSessionIndex.
>Add the following.
public const string DUMMY = "dummy";

This change is already present in FxHttpSessionIndex.cs in SymphonyTeleca/OpenTouryo repository

But below needs to modified in BaseContoller.cs

at OpenTouryo

Session["FxDummy"] = "dummy";  

please confirm

**Comment by daisukenishino** [comment]
@kishoreandukuri 

Modifications to the BaseContoller.cs is unnecessary.
Therefor, Changes of BaseContoller.cs must be reverted.

To do so,
- Discard the current feature branch,
- Create a new feature branch from nishino branch,
- Please send pullrequest that is changed only FxHttpSessionIndex.

**Comment by kishoreandukuri** [comment]
@daisukenishino 

Thank you for the confirmation.
We will do so

**Comment by kishoreandukuri** [comment]
@daisukenishino 

>Please send pullrequest that is changed only FxHttpSessionIndex.

We created pull request
https://github.com/SymphonyTeleca/OpenTouryo/pull/66

This pull request contains the changes of BDLayer test code development

Please review.

**Comment by daisukenishino** [comment]
@kishoreandukuri 

>This pull request contains the changes of BDLayer test code development

Please split the pullrequest.

**Comment by kishoreandukuri** [comment]
@daisukenishino 

>Please split the pullrequest.

Please merge the pull request
https://github.com/SymphonyTeleca/OpenTouryo/pull/68

**Pull request closed without merging**
