### PR TITLE
Renamed the Namespace of silverlight client to generic name.

### PR DESCRIPTION
**Pull request by SandeepNayak077**
The following namespace is changed because the silverlight support is deprecated.
- WSClientSL_sample --> WSClient_sample.

### CODE REVIEW

**Comment by daisukenishino** [comment]
@SandeepNayak077 

This is wrong.

```XML
WSClient_sample.Web...
```
▼ ▼ ▼
```XML
WinStore_sample.Web...
```

**Comment by SandeepNayak077** [comment]
@daisukenishino 

We have given the generic Namespace.
Because the following Namespace are used in other projects like WPF, Win and Win2 samples. 
```XML
WSClient_sample.Web...
```

When user works on WinStore sample then they should change it to <b>WinStore_sample.Web...</b>

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Shall we give instruction to user as following?
```XML
<Transmission id="muWebService" assemblyName="dummy" className="WSClient_sample.Web.Business.LayerB_mu" />
```
▼ ▼ ▼
```XML
<!-- Plesae enter MuWebService Namespace like WSClient_sample.Web.Business.LayerB_mu  -->
<Transmission id="muWebService" assemblyName="dummy" className="MuWebService_Namespace" />
```

Please confirm.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

>Because the following Namespace are used in other projects like WPF, Win and Win2 samples.

If so, this pull request is a problem.
But in fact "WSClient_sample.Web.Business.LayerB_mu" does not exist.

We expect the following changes.

```XML
<Transmission id="muWebService" assemblyName="dummy" className="WSClient_sample.Web.Business.LayerB_mu" />
```
▼ ▼ ▼
```XML
<Transmission id="muWebService" assemblyName="dummy" className="WinStore_sample.Web.Business.LayerB_mu" />
```

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> https://github.com/SymphonyTeleca/OpenTouryo/pull/106#issuecomment-197699366

Ok.
<b>Confirmation</b>
This correspondence is required in all the following files
- /files/resource/Xml/TMInProcessDefinition.xml
- /WSClientWPF_sample/TMInProcessDefinition.xml (C# and VB)
- /WSClientWin2_sample/config/TMInProcessDefinition.xml (C# and VB)
- /WSClientWin_sample/TMInProcessDefinition.xml (C# and VB)

Or 
Only in the /files/resource/Xml/TMInProcessDefinition.xml

Please confirm.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

I want you to the corresponding four files.
- However, the definition of **"WinStore_sample.Web"** is only needed by [/files/resource/Xml/TMInProcessDefinition.xml](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/files/resource/Xml/TMInProcessDefinition.xml) file .
- Therefore, to remove the definition of **"WSClientSL_sample.Web"** from other files.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> https://github.com/SymphonyTeleca/OpenTouryo/pull/106#issuecomment-197706650

Ok we understood.
At present, only the WinStore_sample is using Mu, Sb and Rt web services.
We will modify as described in the above comment and create new pull request.

Thank you for the confirmation.

**Pull request closed without merging**
