### PR TITLE
Fixed the issue identified in Global.asax and App_Code in root for VB

### PR DESCRIPTION
**Pull request by svkumar2810**
1. Changed the class name of inherits in Global.asax as "ProjectX_sample.Global" from "ProjectX_sample.Global_asax"
2. Renamed the App_Code folders name to be "AppCode"

### CODE REVIEW

**Comment by daisukenishino** [comment]
@svkumar2810 

Thank you for quick support.
Please also send for the OpenTouryoTemplate.

**Comment by daisukenishino** [comment]
@svkumar2810 

I'm gonna take off.

Please create pull-request for modification of the OpenTouryoTemplate.
And, please also carry out test to "pass the normal test case" in every root folder.
"pass the normal test case" => To get a list in the CRUD screen.

Please do its best because this is the finish.

**Comment by svkumar2810** [comment]
@daisukenishino 

Sure. we will give our best and we are also performing the test to pass the normal test case.

**Comment by svkumar2810** [comment]
@daisukenishino 

We have completed the changes for OpenTouryoTemplates and created the pull request [#180](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/180)

Please review and merge. 

Thank you for your cooperation and extended support on this.

**Pull request merged**
