### PR TITLE
Converted ProjectX_sample website to webapp

### PR DESCRIPTION
**Pull request by supragyan**
Modified as per below to convert ProjectX_sample website to web application.
1.Deleted ProjectX_sample website and created ProjectX_sample webapp.
2.Included all the files (.aspx,.master,.Css etc) in ProjectX_sample webapp.
3.Modified Inherits attribute to each .aspx page.
4.Changed CodeFile attribute to CodeBehind in each .aspx page.
5.Added namespace to each aspx.cs page. 
6.Created Old_App_Code instaed of App_Code by converting Website to Webapp.
7.Renamed Old_App_code to App_Code to maintain consistency
8.Modified some class as required to support in webapp.

### CODE REVIEW

**Comment by daisukenishino** [comment]
@supragyan 

I have received a problem and question of the evidence from @yusukemaegawa.
Please answer the following items.

# Questions to the evidence
### SampleScreen.aspx

##### **existing Website**  
Table is displayed after accessing the DB with **"existing Website"**

##### **new Webapp**  
Did **"new Webapp"** also succeed to access to the DB ?

### SampleScreen_cc.aspx
Also, this is succeed to access to the DB ?

### WebForm0.aspx
There is only the capture **WebForm0.aspx**.
Is each screens transfered between each screens without  problem ?


# Problems of the evidence
### testRepeater.aspx
Evidence is incorrect.

**Comment by supragyan** [comment]
@daisukenishino 

# Answers to the evidence
## SampleScreen.aspx
>Did "new Webapp" also succeed to access to the DB ?

Yes new  Webapp" also succeed to access to the DB

## SampleScreen_cc.aspx
>Also, this is succeed to access to the DB ?

Yes new  Webapp" also succeed to access to the DB

## WebForm0.aspx
>There is only the capture WebForm0.aspx.
Is each screens transfered between each screens without problem ?

Yes each screens transfered between each screens without problem.

Also each screens has tested properly.

## testRepeater.aspx
>Evidence is incorrect.

Sorry for inconvenience.
For new web app, we have missed the correct evidence.

# Reasons to the problem of evidences 
We have tested each page properly but we have taken only page load screenshots because too many pages are there.

Do we need to take evidence for each page load and accessing to the database screenshots

Please confirm.

**Comment by daisukenishino** [comment]
@supragyan 

Please replace the Evidence of testReperter.aspx.
After confirmation, I will merge this pullrequest.

**Comment by supragyan** [comment]
@daisukenishino 

>Please replace the evidence of testReperter.aspx.

Ok.We will replace and will send you evidence excel sheet..

**Comment by supragyan** [comment]
@daisukenishino 

We have replaced the evidence of testReperter.aspx in Evidence_ProjectX_sample website_webapp_2010  excelsheet.

We also replaced this file in IP Server.
Location: [/Delivery//20160523/].
File Name:Evidence_ProjectX_sample website_webapp_2010

Please review and merge.

**Comment by daisukenishino** [comment]
@supragyan 

Because the conflict has occurred, we can not merge this pull-request.
Please resolve the conflict by pulling "**nishino**" branch from the "**Website-webapp-convertion**" branch.

**Comment by supragyan** [comment]
@daisukenishino 

Ok.I see.

**Comment by supragyan** [comment]
@daisukenishino 

We found the reason of  conflict which occured in this branch.

**Reason of conflict**
We have created [#125](https://github.com/SymphonyTeleca/OpenTouryo/pull/125) for converting Website to Webapp before https://github.com/SymphonyTeleca/OpenTouryo/commit/e74bce58d19bcf0b647d30ac02d6aa895279d4c4 commit.
But https://github.com/SymphonyTeleca/OpenTouryo/commit/e74bce58d19bcf0b647d30ac02d6aa895279d4c4 commit has merged before [#125](https://github.com/SymphonyTeleca/OpenTouryo/pull/125) commit.

So conflicts has occured for Common.js file because the location of Common.js file has changed in [#125](https://github.com/SymphonyTeleca/OpenTouryo/pull/125).

We have resolved this conflict by following below process.
- Created new branch from nishino branch.
- Compare differences with website-webapp-conversion branch and merge the new changes from nishino.branch.
- Copy website-webapp-conversion changes to new branch which created from nishino branch.
- Create pull request to nishino branch.

Please review [#136](https://github.com/SymphonyTeleca/OpenTouryo/pull/136) and merge.

**Pull request closed without merging**
