### PR TITLE
Changed the path of ProjectX_sample web application in C# version.

### PR DESCRIPTION
**Pull request by supragyan**
Modified  the path of ProjectX_sample web application as per review comment.

### CODE REVIEW

**Comment by supragyan** [comment]
@daisukenishino,

Please do not merge this pull request for a while. As the solution file location needs to be changed. I will test and confirm once the changes are done.

**Comment by daisukenishino** [comment]
@supragyan 

>https://github.com/SymphonyTeleca/OpenTouryo/pull/143#issuecomment-234955728

I see.

**Comment by supragyan** [comment]
@daisukenishino 

We have changed the path of ProjectX_sample solution file and tested. 
Please review [#143](https://github.com/SymphonyTeleca/OpenTouryo/pull/143) and let us know.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

Please resolve the conflict by create new feature branch from SymphonyTeleca/OpenTouryo nishino branch and modify this new feature branch.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> https://github.com/SymphonyTeleca/OpenTouryo/pull/143#issuecomment-236107268

It has been resolved.
Please confirm.

**Comment by supragyan** [comment]
@daisukenishino 
Please confirm this pull request.
So that we will proceed to merge for this task.

**Comment by daisukenishino** [comment]
@supragyan 

Evidence is required.
Check the e-mail.

**Comment by supragyan** [comment]
@daisukenishino 
>Evidence is required.
Check the e-mail.

Ok we will send evidence

**Pull request merged**
