### PR TITLE
Repositioned the properties in the resource file

### PR DESCRIPTION
**Pull request by SandeepNayak077**
This change is required because to synchronise easlily with root with root_VS2010-root_VS2015.

In [this commit](https://github.com/SymphonyTeleca/OpenTouryo/pull/94/commits/c9f868b3c254b6906cc75500198d9fd07776dc2b), the position of many properties are changed.

This was causing lots of difference check while merging.
So we have synchronised root version with the other versions (root_VS2010-root_VS2015).
However we have not changed the values only the position has been changed.
And we also successfully performed UI testing.

Please review and merge this pull request.

### CODE REVIEW

**Comment by daisukenishino** [comment]
@SandeepNayak077 

Is this pullrequest related with what issue number ?

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> Is this pullrequest related with what issue number ?

The issue number is [#139](https://github.com/OpenTouryoProject/OpenTouryo/issues/139).

Please refere [this comment](https://github.com/OpenTouryoProject/OpenTouryo/issues/139#issuecomment-178272799),
You have requested to change the order of items.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

The new changes can be compared by performing the Winmerge between root and root_VS2010.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

We are requesting to merge this code ASAP.
This might delay the merge activity.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

It had been described as follows in the evidence report,

```TXT
- Before changing the positions of resource elements in the Form2.ja-JP.resx
- After changing the positions of resource elements in the Form2.ja-JP.resx
- Both are same - No change in the UI
```

But, I think that the size of the control have a problem.

image

Please send an additional pull request to fix this.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> https://github.com/SymphonyTeleca/OpenTouryo/pull/109#issuecomment-199564444
> But, I think that the size of the control have a problem.

We have checked the font size of the checkbox control, but there is no problem.

Are you refering to the following large space between the checkbox control and the container?
size_issue

Please confirm.

**Comment by yusukemaegawa** [comment]
@SandeepNayak077 

You set the value of resource as follows.

```xml
<data name="cbxTableMaintenance.Text" xml:space="preserve">
    <value>テーブルメンテナンス画面を生成します。</value>
</data>
```

So, "テーブルメンテナンス画面を生成**します。**" should be displayed for the text of checkbox.
But, from screen capture, you can see that "テーブルメンテナンス画面を生成**しま**" is currently displayed for the text of checkbox.
(The last "**す。**" is not displayed.)

**Comment by daisukenishino** [comment]
@SandeepNayak077 

>Are you refering to the following large space between the checkbox control and the container?

No, the string is lacking.

incorrect : "テーブルメンテナンス画面を生成しま"
▼ ▼ ▼
correct : "テーブルメンテナンス画面を生成します。"
```XML
<data name="cbxTableMaintenance.Text" xml:space="preserve">
  <value>テーブルメンテナンス画面を生成します。</value>
</data>
```

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> https://github.com/SymphonyTeleca/OpenTouryo/pull/109#issuecomment-199681135
> https://github.com/SymphonyTeleca/OpenTouryo/pull/109#issuecomment-199681323

Oh I see.
We got it, the last Japanese character is not displaying.
So, we need to increase the length of the control.
Thank you for the information.
We will send this correspondence with new pull request.

**Pull request merged**
