### PR TITLE
Enhance of MyBaseMVCController

### PR DESCRIPTION
**Pull request by kishoreandukuri**
Did Enhance of MyBaseMVController
https://github.com/OpenTouryoProject/OpenTouryo/issues/118

1)An erroneous detection of the session time-out
2)Added new constant DUMMY to the class FxHttpSessionIndex.cs
3)Stored dummy value in session to fix the bug in OnActionExecuting method

### CODE REVIEW

**Comment by daisukenishino** [comment]
@kishoreandukuri 
Conflict has occurred.
Please resolve conflicts between the branch.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
We have manually merged the changes and did commit.
it is showing the below message now 
'This branch is up-to-date with the base branch
Merging can be performed automatically.'
Please review the pull request now.

**Comment by daisukenishino** [comment]
@kishoreandukuri 

Thank you.
I appreciate your support.

**Comment by kishoreandukuri** [comment]
@daisukenishino 

you are welcome

**Comment by daisukenishino** [comment]
@kishoreandukuri 

There is a problem in this pullrequest.

It is because this pullrequest contains change of 
- BD Layer test code Improvement
- and DPQuery_Tool
- and MyBaseMVController.

The reason,
I think that it's because nishino branch has not received these pullrequest.

I will push the "/OpenTouryoProject/OpenTouryo/tree/develop/" to nishino branch for resolution.
And, we will close this pullrequest.

**Comment by daisukenishino** [comment]
@kishoreandukuri 
I pushed the "/OpenTouryoProject/OpenTouryo/tree/develop/" branch to nishino branch for resolution. I think you were generated EnhanceMyBaseMVController feature branch from "/OpenTouryoProject/OpenTouryo/develop/" branch. Therefore, we believe that the solution by sending a pullrequest again.

**Comment by kishoreandukuri** [comment]
@daisukenishino 

we created below pull request again as per the above comments

https://github.com/SymphonyTeleca/OpenTouryo/pull/65

please review

**Pull request closed without merging**
