### PR TITLE
Fixed the issue identified in Global.asax and App_Code in root C#

### PR DESCRIPTION
**Pull request by svkumar2810**
1. Changed the class name of inherits in Global.asax as "ProjectX_sample.Global" from "ProjectX_sample.Global_asax" 
2. Renamed the App_Code folders name to be "AppCode"

### CODE REVIEW

**Comment by daisukenishino** [comment]
@svkumar2810 

Thank you for support.
Please also send for the VB version.

**Comment by svkumar2810** [comment]
@daisukenishino 

The issue identified only in C#. There is no issue in VB. Please let me know if you still want me to modify the VB.

**Comment by daisukenishino** [comment]
@svkumar2810 

Please perform the following to VB.
- Changed the class name in Global.asax and Global.asax.vb  
as "ProjectX_sample.Global" from "ProjectX_sample.Global_asax"
- Renamed the App_Code folders name to be "AppCode"

**Comment by svkumar2810** [comment]
@daisukenishino 

>- Changed the class name in Global.asax and Global.asax.vb
as "ProjectX_sample.Global" from "ProjectX_sample.Global_asax"

We cannot rename to ProjectX_sample.Global in Vb as error is prompted  as **Keyword is not valid as an identifier**	. By default the file will be added as Global_asax. So we think this change is not required.

>- Renamed the App_Code folders name to be "AppCode"

I believe we can rename App_Code to "AppCode". 

Please confirm

**Comment by daisukenishino** [comment]
@svkumar2810 

>We cannot rename to ProjectX_sample.Global in Vb as error is prompted as Keyword is not valid as an identifier. By default the file will be added as Global_asax. So we think this change is not required.

There is a need to be the same name.

Please modify as follows.

### Global.asax
```VB
<%@ Application Codebehind="Global.asax.vb" Inherits="ProjectX_sample.Global" Language="vb" %>
```
### Global.asax.vb
```VB
Public Class [Global]
    Inherits System.Web.HttpApplication
```

**Comment by svkumar2810** [comment]
@daisukenishino 

We have modified as suggested in VB and created  new pull request [#150](https://github.com/SymphonyTeleca/OpenTouryo/pull/150).

Thanks for your cooperation.
Please review and merge.

I will be modifying the similar changes in OpenTouryoTemplate and send you a separate pull request.

**Pull request merged**
