### PR TITLE
Deprecated the support of Silver light and XBAP from the root version

### PR DESCRIPTION
**Pull request by SandeepNayak077**
Removed the following projects
- WSClientSL_samples
- WSClientWPFbap_sample

### CODE REVIEW

**Comment by yusukemaegawa** [comment]
@SandeepNayak077 

Please also check the batch files that build WSClientSL_samples and WSClientWPFbap_sample.

**Comment by SandeepNayak077** [comment]
@yusukemaegawa 
@daisukenishino 

> https://github.com/SymphonyTeleca/OpenTouryo/pull/98#issuecomment-190973588
> Please also check the batch files that build WSClientSL_samples and WSClientWPFbap_sample.

Oh yes, thank you for the information.
I am closing this pull request and will create new pull request by cleaning the related batch files.

Shall we remove the Portable Class Library from root and root_VS2010 versions?
Because PCL support requires only for WSClientSL_samples in these versions.
please confirm.

**Comment by yusukemaegawa** [comment]
@SandeepNayak077 

>I am closing this pull request and will create new pull request by cleaning the related batch files.

Thank you in advance.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

>Shall we remove the Portable Class Library from root and root_VS2010 versions?
Because PCL support requires only for WSClientSL_samples in these versions.
please confirm.

Please leave PCL, because there is a possibility that it will be used in .NET Compact Framework.

**Comment by SandeepNayak077** [comment]
@yusukemaegawa 
@daisukenishino 

Thank you for your support.

**Pull request closed without merging**
