### PR TITLE
Implemented IDbCommand for multiple db support

### PR DESCRIPTION
**Pull request by kishoreandukuri**
1) Added abstract property of IDbCommand in BaseDam.cs
2) Overrode the property of IDbCommand in DamODBC.cs, DamOLEDB.cs, DamOraClient.cs and DamSqlSvr.cs

### CODE REVIEW

**Comment by daisukenishino** [comment]
BaseDam is not a modification of the target.
Instead, there is a need to modify the following modules.
 - CmnDao.cs and .vb
 - DaoTemplate.cs and .vb

Also please fixes for the following modules.
 - DamOraOdp
 - DamMySQL
 - DamPstGrS
 - DamDB2
 - DamHiRDB

Do not Delete the following methods to maintain backward compatibility.
 - public OdbcCommand DamOdbcCommand
 - public OleDbCommand DamOleDbCommand
 - public OracleCommand DamOracleCommand
 - public SqlCommand DamSqlCommand

**Comment by kishoreandukuri** [comment]
Dear Nishino-san,

Thank you for reviewing the code.
HODC will work on the above changes

Thanks,

**Comment by kishoreandukuri** [comment]
Dear Nishino-san,

HODC modified the method  in CmnDao.cs

 /// <summary>To Set CommandTimeout</summary>
        private void SetCommandTimeout()
        {
            // If CommandTimeout is >= 0 then set CommandTimeout.
            // Else skip, automatically it will set default CommandTimeout.
            if (this._commandTimeout >= 0)
            {
                (((DamSqlSvr)this.GetDam()).DamIDbCommand).CommandTimeout = this._commandTimeout;
            }
        }


modified method on DamSqlSvr.cs

 /// <summary>SQL文とCommandTypeを設定して、Commandオブジェクトを生成。</summary>
        /// <param name="commandText">実行するSQL文</param>
        /// <param name="commandType">コマンドの種類</param>
        /// <remarks>通常、Ｄａｏ経由で利用する。</remarks>
        public override void SetSqlByCommand(string commandText, CommandType commandType)
        {
            // コマンド テキストが、動的パラメタライズド クエリであるか確認する。
            // 結果は、プロパティに保存される。
            this.CheckCommandText(commandText);

            // Commandオブジェクトを生成する
            this._cmd = new SqlCommand();
            this._cmd.CommandText = commandText;
            this._cmd.CommandType = commandType;

            // システム共通のCommandTimeout値を設定する。
            this.SetCommandTimeout(<b>DamIDbCommand</b>); // #x-この行
        }

**Comment by daisukenishino** [comment]
>BaseDam is not a modification of the target.
This is incorrect.
It will only implement the following methods.
```C#
public abstract IDbCommand DamIDbCommand
```

>1) method in CmnDao.cs
That's right.
Please use the DamIDbCommand property.

>2) modified method on DamSqlSvr.cs
There is no need to modify the inside of SetSqlByCommand method.
It is necessary only override DamIDbCommand.

Please point out if there is a problem with my instructions.

**Comment by kishoreandukuri** [comment]
Dear Nishino-san,

Thank you for the comments.

HODC will do the changes and check whether there is any problem in implementation.

Thanks,

**Pull request closed without merging**
